### ISSUE TITLE
There is no memory in the system to complete the operation (IN_OPENRESULT_NOMEMORY)

### ISSUE THREAD

**Issue by toby11** [melanchall/drywetmidi#160]
Sometimes on InputDevice when calling StartEventsListening

I get this exception

`Melanchall.DryWetMidi.Multimedia.MidiDeviceException: There is no memory in the system to complete the operation (IN_OPENRESULT_NOMEMORY).
   at Melanchall.DryWetMidi.Multimedia.NativeApi.HandleResult[TResult,TException](TResult result, Func`3 createException)
   at Melanchall.DryWetMidi.Multimedia.NativeApiUtilities.HandleDevicesNativeApiResult[TResult](TResult result)
   at Melanchall.DryWetMidi.Multimedia.InputDevice.EnsureHandleIsCreated()
   at Melanchall.DryWetMidi.Multimedia.InputDevice.StartEventsListening()
   at MidiListener.PreSonusMidiController.StartMidiListening() in D:\Development\C Sharp\Midi\MidiListener\MidiController.cs:line 110`

Windows 10 x86 compiled c# code

using 6.1.0-prerelease2 nuget but I was getting the same error in 6.0.1

and I have about 15GB free memory.

**Comment by melanchall** [comment]
Hi,

Please show your code how you work with `InputDevice`. Are you sure you dispose it when you are done with it?

This error is internal one of Windows MIDI subsystem. DryWetMIDI just redirects it from operating system to you. My assumption is you're not correctly closing a device and thus you have attempt to open a device which was already open and is not properly closed.

**Comment by toby11** [comment]
thanks yes I have found that there was a crashed instance on my application running which must have locked the midi device - thanks anyway.
