### ISSUE TITLE
MidiDeviceException Internal error

### ISSUE THREAD

**Issue by mystery123sk** [melanchall/drywetmidi#272]
Hi,

I'm getting this crash log from my client's computer:

Exception to string:Melanchall.DryWetMidi.Multimedia.MidiDeviceException: Internal error (IN_OPENRESULT_UNKNOWNERROR).
at Melanchall.DryWetMidi.Multimedia.NativeApi.HandleResult[TResult,TException](TResult result, Func`3 createException)
at Melanchall.DryWetMidi.Multimedia.InputDevice.EnsureHandleIsCreated()
at Melanchall.DryWetMidi.Multimedia.InputDevice.StartEventsListening()

What the software is trying to do, when this exception is received, is to restart all USB devices, when USB connection/disconnection happens in Windows. In the WndProc I receive WM_DEVICECHANGE message and I close all the Midi devices and reopen them.

Any idea, how I can find out more about the reason? And ideally how I could fix it?

**Comment by melanchall** [comment]
Hi,

First of all, it's the error from Windows, not from the DryWetMIDI. And you'll get it with any other library. I suppose it's prohibited to do what you do within device changed.

But can you please show the code of your `WndProc`?

**Comment by melanchall** [comment]
Please put yourself in my shoes. I have no idea what `IsOpen`, `Close` and `Start` are. There are no such methods in DryWetMIDI on devices. I don't see how you use my code. Show how all this your API is implemented.

Also

> It crashes on the last line of this method, following call stack:

This line?

```csharp
devices.FirstOrDefault(d => d.Name == dID)?.Start();
```

In this case it's even stranger that you didn't show me how `Start` method is implemented.

Also you obviously should check whether the problem is related to any device or specific one.

Please read this article: https://melanchall.github.io/drywetmidi/articles/dev/Support.html. Your problem is obviously not a bug of the library. But I'm trying to help you anyway. Please help me too.

More than that, your code looks really strange for me:

```csharp
if (d.IsOpen)
    openedDevices.Add(d.Name);
d.Close();
```

So if device is open, you just add it to the list. And close it... in both case, when it's opened and when it's closed? Is this OK to close already closed device?

```csharp
//restart opened devices
foreach (var dID in openedDevices)
    devices.FirstOrDefault(d => d.Name == dID)?.Start();
```

Again pretty strange code. You start devices that are already "started"/"opened".

**Comment by mystery123sk** [comment]
Yes, sorry for that, I have several layers, which would complicate the explanation. This is the Start method:

		public void Start()
		{
			lock (this)
			{
				if (isStarted || device == null)
					return;

				if (device is InputDevice)
				{
					var d = (InputDevice)device;
					d.EventReceived += MidiEventReceived;
					d.MidiTimeCodeReceived += OnMidiTimeCodeReceived;
					d.StartEventsListening();
				}

				if (device is OutputDevice)
				{
					var d = (OutputDevice)device;
					d.PrepareForEventsSending();
				}

				EZLogger.Info($"Midi opened {this.ToString()}");
				isStarted = true;
			}
		}

The latest exception I get (from client's computer) is this:

Exception to string:Melanchall.DryWetMidi.Multimedia.MidiDeviceException: Internal error (IN_OPENRESULT_UNKNOWNERROR).
at Melanchall.DryWetMidi.Multimedia.NativeApi.HandleResult[TResult,TException](TResult result, Func`3 createException)
at Melanchall.DryWetMidi.Multimedia.InputDevice.EnsureHandleIsCreated()
at Melanchall.DryWetMidi.Multimedia.InputDevice.StartEventsListening()

Sometimes I also receive this kind of exception:

Exception to string:Melanchall.DryWetMidi.Multimedia.MidiDeviceException: There is no memory in the system to complete the operation (IN_OPENRESULT_NOMEMORY).
at Melanchall.DryWetMidi.Multimedia.NativeApi.HandleResult[TResult,TException](TResult result, Func`3 createException)
at Melanchall.DryWetMidi.Multimedia.InputDevice.EnsureHandleIsCreated()
at Melanchall.DryWetMidi.Multimedia.InputDevice.StartEventsListening()

The Start methods in my code handle the opened devices as you can see (doesn't start it again).

**Comment by melanchall** [comment]
> What the software is trying to do, when this exception is received, is to restart all USB devices, when USB connection/disconnection happens in Windows. In the WndProc I receive WM_DEVICECHANGE message and I close all the Midi devices and reopen them.

First of all, that's OK you work with **ALL** MIDI devices? Is your software about managing all devices at once?

Also I wrote above:

> Also you obviously should check whether the problem is related to any device or specific one.

So this exception occurs on any device or specific one? What's the name of a device the exception occurs on? Maybe you receive `WM_DEVICECHANGE` for device X and in `WndProc` you try to start it and it crashes? So is the exception related only to device which causes `WM_DEVICECHANGE` or not?

**Comment by mystery123sk** [comment]
The problem appears only on client's computer (in USA, I stay in Europe) - I don't have a chance to test it. I just receive crash logs and I'm trying to figure out, what's wrong. And yes, I can receive events from all the devices (if client decides to do so), but I start only devices, which are actually used.

The client has only one Midi device (Akai APC Mini), doesn't have an option trying several. 

The computer he's using is really slow (some old Celeron 1.1 Ghz). I'm not sure, if this could be relevant.

**Comment by melanchall** [comment]
> The client has only one Midi device (Akai APC Mini), doesn't have an option trying several.

So we can safely assume that his devices collections within your software are always of one item, yes?

Can you confirm this steps:

1. The user plugs the device X.
2. Your software calls `Start` on X.
3. At some point of time you receive `WM_DEVICECHANGE` about X.
4. You close X and start it again within `WndProc`.

Is that what happen?

**Comment by melanchall** [comment]
@mystery123sk Any news?

**Comment by mystery123sk** [comment]
Hi, no news - the client used other computer and there it works. Thank you for your help, for now I think you can close this. I don't have an option to test it further in detail.
